apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 2000
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":\s*"([0-9a-f]{32})"'
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: View trace
        - name: SpanID
          matcherRegex: '"span_id":\s*"([0-9a-f]{16})"'

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-30s'
        spanEndTimeShift: '30s'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{service_name="$${__span.tags["service.name"]}"} | json | trace_id="$${__trace.traceId}"'
      tracesToMetrics:
        datasourceUid: mimir
        spanStartTimeShift: '-2m'
        spanEndTimeShift: '2m'
        tags:
          - key: service.name
            value: service
        queries:
          - name: Span rate
            query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m]))'
          - name: Span errors
            query: 'sum(rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR",$$__tags}[5m]))'
          - name: Span latency p95
            query: 'histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m])) by (le))'
      serviceMap:
        datasourceUid: mimir
      nodeGraph:
        enabled: true
      search:
        hide: false
      streamingEnabled:
        search: true

  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Mimir
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
